"""
PDF Report Generator (Step 10)

Kid explanation:
    Everything so far lives on a webpage. This module packages the same
    information -- the diagnosis, the numbers, the chart -- into an
    actual PDF file, like the printed report card a real inspector
    would leave behind after checking your machine. Someone can
    download it, email it, or print it, without needing to open the
    website at all.
"""
import io

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image,
)

HEALTH_COLORS = {
    "healthy": colors.HexColor("#22543d"),
    "watch": colors.HexColor("#744210"),
    "warning": colors.HexColor("#822727"),
}
HEALTH_LABELS = {
    "healthy": "HEALTHY",
    "watch": "WATCH",
    "warning": "WARNING",
}


def generate_pdf_bytes(scan_data: dict) -> bytes:
    """
    Main entry point for Step 10.

    `scan_data` is a plain dict (rather than requiring a Django Scan
    instance directly) so this stays testable standalone. Expected keys:
        machine_name, created_at (str), health_status,
        dominant_frequency_hz, amplitude, diagnosis_text,
        chart_image_path (optional, absolute path to a PNG on disk)

    Returns the PDF file's raw bytes, ready to save to disk or attach
    to a Django FileField.
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=letter,
        topMargin=0.75 * inch, bottomMargin=0.75 * inch,
        leftMargin=0.75 * inch, rightMargin=0.75 * inch,
    )
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "ReportTitle", parent=styles["Title"], fontSize=20, spaceAfter=4,
    )
    subtitle_style = ParagraphStyle(
        "ReportSubtitle", parent=styles["Normal"], fontSize=11,
        textColor=colors.HexColor("#555555"), spaceAfter=18,
    )
    section_style = ParagraphStyle(
        "SectionHeading", parent=styles["Heading2"], spaceBefore=14, spaceAfter=6,
    )
    body_style = styles["Normal"]
    disclaimer_style = ParagraphStyle(
        "Disclaimer", parent=styles["Normal"], fontSize=8,
        textColor=colors.HexColor("#888888"), spaceBefore=20,
    )

    story = []

    # --- Header ---
    story.append(Paragraph("Machine Doctor — Vibration Diagnostic Report", title_style))
    story.append(Paragraph(
        f"Machine: {scan_data['machine_name']} &nbsp;&nbsp;|&nbsp;&nbsp; "
        f"Scan date: {scan_data['created_at']}",
        subtitle_style,
    ))

    # --- Health status banner ---
    health = scan_data.get("health_status", "watch")
    health_label = HEALTH_LABELS.get(health, health.upper())
    health_color = HEALTH_COLORS.get(health, colors.grey)
    health_style = ParagraphStyle(
        "HealthBanner", parent=styles["Normal"], fontSize=14,
        textColor=health_color, spaceAfter=12,
    )
    story.append(Paragraph(f"Overall Status: <b>{health_label}</b>", health_style))

    # --- Key metrics table ---
    metrics_data = [
        ["Metric", "Value"],
        ["Dominant Frequency", f"{scan_data.get('dominant_frequency_hz', '—')} Hz"],
        ["Amplitude", f"{scan_data.get('amplitude', '—')}"],
    ]
    metrics_table = Table(metrics_data, colWidths=[2.5 * inch, 3 * inch])
    metrics_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2b6cb0")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#dddddd")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f7fafc")]),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(metrics_table)

    # --- Diagnosis ---
    story.append(Paragraph("Diagnosis", section_style))
    story.append(Paragraph(scan_data.get("diagnosis_text", "No diagnosis available."), body_style))

    # --- Chart ---
    chart_path = scan_data.get("chart_image_path")
    if chart_path:
        story.append(Paragraph("Vibration Frequency Spectrum", section_style))
        # Fit the chart to the page width while preserving its aspect ratio
        img = Image(chart_path)
        max_width = 6.0 * inch
        aspect = img.imageHeight / float(img.imageWidth)
        img.drawWidth = max_width
        img.drawHeight = max_width * aspect
        story.append(img)

    # --- Disclaimer ---
    story.append(Paragraph(
        "This report was generated by an automated, non-contact video-based vibration "
        "analysis prototype for demonstration purposes. Amplitude values are in relative, "
        "uncalibrated units, not calibrated physical units (e.g. mm/s or g). This is not a "
        "certified inspection and should not replace professional equipment maintenance judgment.",
        disclaimer_style,
    ))

    doc.build(story)
    buf.seek(0)
    return buf.read()