# Generated by Django 5.0.6 on 2026-08-24 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaultPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('freq_min_hz', models.FloatField()),
                ('freq_max_hz', models.FloatField()),
                ('amplitude_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('description', models.TextField(help_text='Plain-English description shown to the user')),
                ('recommendation', models.TextField(help_text='What the user should do about it')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A friendly name, e.g. 'Kitchen Exhaust Fan'", max_length=100)),
                ('machine_type', models.CharField(blank=True, help_text="Optional category, e.g. 'fan', 'motor', 'compressor'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='uploads/videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dominant_frequency_hz', models.FloatField(blank=True, help_text='The strongest vibration frequency found by FFT', null=True)),
                ('amplitude', models.FloatField(blank=True, help_text='How big the vibration is (arbitrary pixel-motion units)', null=True)),
                ('camera_shake_removed', models.BooleanField(default=False, help_text='Whether ego-motion filtering successfully ran')),
                ('diagnosis_text', models.TextField(blank=True)),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('watch', 'Watch'), ('warning', 'Warning')], default='healthy', max_length=20)),
                ('chart_image', models.ImageField(blank=True, null=True, upload_to='charts/')),
                ('report_pdf', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='scanner.machine')),
                ('matched_fault_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanner.faultpattern')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
