# Generated by Django 5.0.6 on 2026-08-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faultpattern',
            name='health_status',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('watch', 'Watch'), ('warning', 'Warning')], default='watch', help_text='How serious this fault is, used to color-code the dashboard', max_length=20),
        ),
        migrations.AddField(
            model_name='scan',
            name='magnified_video',
            field=models.FileField(blank=True, null=True, upload_to='magnified/'),
        ),
    ]
